define([//'./example/hello',
        //'./example/hi',
        //'./example/search',
        './components/accordion',
        './components/affix',
        './components/alert',
        './components/badge',
        './components/button',
        './components/buttonGroup',
        './components/buttonInput',
        './components/buttonToolbar',
        './components/carousel',
        './components/carouselItem',
        './components/col',
        './components/collapsibleNav',
        './components/dropdownButton',
        './components/formGroup',
        './components/glyphicon',
        './components/grid',
        './components/input',
        './components/interpolate',
        './components/jumbotron',
        './components/label',
        './components/linkWithTooltip',
        './components/listGroup',
        './components/listGroupItem',
        './components/menuItem',
        './components/modal',
        './components/modalTrigger',
        './components/nav',
        './components/navbar',
        './components/navItem',
        './components/overlayTrigger',
        './components/pageHeader',
        './components/pageItem',
        './components/pager',
        './components/panel',
        './components/panelGroup',
        './components/popover',
        './components/progressBar',
        './components/row',
        './components/splitButton',
        './components/subNav',
        './components/tabbedArea',
        './components/table',
        './components/tabPane',
        './components/toolTips',
        './components/well'],
function(/*Hello, Hi, Search, */
  Accordion,
  Affix,
  Alert,
  Badge,
  Button,
  ButtonGroup,
  ButtonInput,
  ButtonToolbar,
  Carousel,
  CarouselItem,
  Col,
  CollapsibleNav,
  DropdownButton,
  FormGroup,
  Glyphicon,
  Grid,
  Input,
  Interpolate,
  Jumbotron,
  Label,
  LinkWithTooltip,
  ListGroup,
  ListGroupItem,
  MenuItem,
  Modal,
  ModalTrigger,
  Nav,
  Navbar,
  NavItem,
  OverlayTrigger,
  PageHeader,
  PageItem,
  Pager,
  Panel,
  PanelGroup,
  Popover,
  ProgressBar,
  Row,
  SplitButton,
  SubNav,
  TabbedArea,
  Table,
  TabPane,
  ToolTips,
  Well) {
  return {
    /*Hello: Hello,
    Hi: Hi,
    Search: Search,*/
    Accordion: Accordion,
    Affix: Affix,
    Alert: Alert,
    Badge: Badge,
    Button: Button,
    ButtonGroup: ButtonGroup,
    ButtonInput: ButtonInput,
    ButtonToolbar: ButtonToolbar,
    Carousel: Carousel,
    CarouselItem: CarouselItem,
    Col: Col,
    CollapsibleNav: CollapsibleNav,
    DropdownButton: DropdownButton,
    FormGroup: FormGroup,
    Glyphicon: Glyphicon,
    Grid: Grid,
    Input: Input,
    Interpolate: Interpolate,
    Jumbotron: Jumbotron,
    Label: Label,
    LinkWithTooltip: LinkWithTooltip,
    ListGroup: ListGroup,
    ListGroupItem: ListGroupItem,
    MenuItem: MenuItem,
    Modal: Modal,
    ModalTrigger: ModalTrigger,
    Nav: Nav,
    Navbar: Navbar,
    NavItem: NavItem,
    OverlayTrigger: OverlayTrigger,
    PageHeader: PageHeader,
    PageItem: PageItem,
    Pager: Pager,
    Panel: Panel,
    PanelGroup: PanelGroup,
    Popover: Popover,
    ProgressBar: ProgressBar,
    Row: Row,
    SplitButton: SplitButton,
    SubNav: SubNav,
    TabbedArea: TabbedArea,
    Table: Table,
    TabPane: TabPane,
    ToolTips: ToolTips,
    Well: Well
  };
});
